config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
    match "posts/data", :to => "posts#data", :as => "data", :via => "get"
    match "posts/db_action", :to => "posts#db_action", :as => "db_action", :via => "get"
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, presence: true

    belongs_to :user
end

app/controllers/posts_controller.rb
require 'simple_calendar'
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]
  def check_user
       # 유저 전체 데이터가 현재 로그인 되어있는 유저와 다르면 root_path로 돌려보내라
    redirect_to root_path, notice: '권한이없습니다' and return unless @post.user == current_user
  end
  
  def data
    events = Event.all
    render :json => events.map {|event| {
            :id => event.id,
            :start_date => event.start_date.to_formatted_s(:db),
            :end_date => event.end_date.to_formatted_s(:db),
            :text => event.text
        }}
  end
  
  #db_action
  def db_action
    mode = params["!nativeeditor_status"]
    id = params["id"]
    start_date = params["start_date"]
    end_date = params["end_date"]
    text = params["text"]

    case mode
      when "inserted"
        event = Event.create :start_date => start_date, :end_date => end_date, :text => text
        tid = event.id

      when "deleted"
        Event.find(id).destroy
        tid = id

      when "updated"
        event = Event.find(id)
        event.start_date = start_date
        event.end_date = end_date
        event.text = text
        event.save
        tid = id
      end

      render :json => {
                  :type => mode,
                  :sid => id,
                  :tid => tid,
              }
  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # @post = Post.new(post_params)
    # 현 유저의 포스트를 새로 만든다. 
    @post = current_user.posts.new(post_params)

    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :interval, :starttime, :fintime, :startday, :days)
    end
    
    
    
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
 <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
 <div class="dhx_cal_navline">
   <div class="dhx_cal_prev_button">&nbsp;</div>
   <div class="dhx_cal_next_button">&nbsp;</div>
   <div class="dhx_cal_today_button"></div>
   <div class="dhx_cal_date"></div>
   <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
   <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
   <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
 </div>
 <div class="dhx_cal_header">
 </div>
 <div class="dhx_cal_data">
 </div>
</div>

<script>
    scheduler.config.xml_date="%Y-%m-%d %H:%i";
    scheduler.init("scheduler_here");
    // scheduler.load("<#%= data_path %>", "json");
    // var dp = new dataProcessor('<%#= db_action_path %>');
    // dp.init(scheduler);
    // dp.setTransactionMode("GET", false);
    
    
</script>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class=nanumbrushscript>공감 시간</h1>

<table class=nanumpenscript>
  <thead>
    <tr>
      <th class="menu">제목</th>
      <th class="menu">사용자</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <!--<td><%#= post.content %></td>-->
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<!--<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>-->
<!-- <div class="dhx_cal_navline">-->
<!--   <div class="dhx_cal_prev_button">&nbsp;</div>-->
<!--   <div class="dhx_cal_next_button">&nbsp;</div>-->
<!--   <div class="dhx_cal_today_button"></div>-->
<!--   <div class="dhx_cal_date"></div>-->
<!--   <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>-->
<!--   <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>-->
<!--   <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>-->
<!-- </div>-->
<!-- <div class="dhx_cal_header">-->
<!-- </div>-->
<!-- <div class="dhx_cal_data">-->
<!-- </div>-->
<!--</div>-->

<!--<script>-->
<!--    scheduler.config.xml_date="%Y-%m-%d %H:%i";-->
<!--    scheduler.init("scheduler_here");-->
<!--    scheduler.load("<%= data_path %>", "json");-->
<!--    var dp = new dataProcessor('<%= db_action_path %>');-->
<!--    dp.init(scheduler);-->
<!--    dp.setTransactionMode("GET", false);-->
    
    
<!--</script>-->

app/views/posts/new.html.erb
<h1>New Post</h1>
  
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% stylesheet_link_tag "show" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

 <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
 <div class="dhx_cal_navline">
   <div class="dhx_cal_prev_button">&nbsp;</div>
   <div class="dhx_cal_next_button">&nbsp;</div>
   <div class="dhx_cal_today_button"></div>
   <div class="dhx_cal_date"></div>
   <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
   <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
   <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
 </div>
 <div class="dhx_cal_header">
 </div>
 <div class="dhx_cal_data">
 </div>
</div>

<script>
    scheduler.config.xml_date="%Y-%m-%d %H:%i";
    scheduler.init("scheduler_here");
    scheduler.load("<%= data_path %>", "json");
    var dp = new dataProcessor('<%= db_action_path %>');
    dp.init(scheduler);
    dp.setTransactionMode("GET", false);
    
    
</script>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>